specVersion: 0.2.0
name: subql-test
version: 1.0.0
description: A test for subquery event collection for contracts pallet
repository: https://github.com/VargSupercolony/subquery-test
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xaad0a356583639efb3fe531f4519aca53cfbc4a8c3b736eb137c7dce7bce7ca8'
  endpoint: wss://ws.jupiter-poa.patract.cn/
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler