specVersion: 0.2.0
name: subql-test
version: 1.0.0
description: A test for subquery event collection for contracts pallet
repository: https://github.com/VargSupercolony/subquery-test
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x4fb18bcea287ce4d014e093bbb028760b6d6e9c935709d07f38039c7b12d6d6e'
  endpoint: wss://ws.jupiter-poa.patract.cn
dataSources:
  - kind: substrate/Runtime
    startBlock: 2465500
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler